version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: demo_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    container_name: backend_container
    environment:
      DB_HOST: mysql
      DB_USER: testuser
      DB_PASSWORD: testpassword
      DB_NAME: testdb
      DB_PORT: 3306:3306
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend/todolist
    container_name: frontend_container
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
